FROM oracle/graalvm-ce:19.0.0 AS builder
RUN gu install native-image

WORKDIR /root
COPY --from=mikeldpl/moneytransfer /root/money-transfer-1.0.jar .
RUN native-image --static --no-fallback -jar money-transfer-1.0.jar

#FROM alpine
FROM ubuntu
MAINTAINER mikeldpl

EXPOSE 4567
WORKDIR /root
COPY --from=builder /root/money-transfer-1.0 .
CMD ["./money-transfer-1.0"]
